service: TodoService

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
          Resource:
            - { "Fn::GetAtt": ["TodoTable", "Arn"] }

functions:
  createTodo:
    handler: src/handlers.createTodo
    events:
      - httpApi:
          path: /todo
          method: post

  getTodos:
    handler: src/handlers.getTodos
    events:
      - httpApi:
          path: /todo
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
